export const CONTENT = {
  esp: {
    siteTitle: 'PRAGMAGICKA',
    subtitle: 'Magia y acción',
    heroSubtitle: 'Magia y acción',
    heroBody: 'Tecnología & magia para tomar decisiones, destrabar la mente y accionar en el mundo real. Sin adivinación. Sin falsas promesas.',
    nav: {
      tarot: 'Lecturas de Tarot',
      resources: 'Recursos Educativos',
      about: 'Sobre Pragmagicka',
      info: 'Info',
    },
    tarotSection: {
      title: 'Lecturas de Tarot',
      subtitle: 'Entiende tus procesos y cómo accionar en pro de tus deseos. Resuelve inquietudes y conócete mejor.',
      additionalQuestionNotice: 'Hacer más de 1 pregunta conlleva un gasto adicional.',
      bookButton: 'Agendar Lectura',
      plans: [
        {
          id: 'tarot-written',
          title: 'Lectura por escrito',
          priceUSD: 29,
          format: 'written' as const,
          questionsCount: 1,
          features: [
            'Fotografía de tu lectura',
            'Un hermoso PDF con todas las respuestas',
            '1 pregunta por lectura (hacer más de 1 pregunta conlleva un gasto adicional)',
          ],
        },
        {
          id: 'tarot-voice',
          title: 'Lectura por nota de voz',
          priceUSD: 56,
          format: 'voice' as const,
          questionsCount: 1,
          popular: true,
          features: [
            'Fotografía de tu lectura',
            'Respaldo por si se te pierde y la necesitas de vuelta',
            '1 pregunta por lectura (hacer más de 1 pregunta conlleva un gasto adicional)',
          ],
        },
        {
          id: 'tarot-videocall',
          title: 'Lectura por videollamada',
          priceUSD: 83,
          format: 'videocall' as const,
          questionsCount: 3,
          duration: '45min a 1hr',
          features: [
            'Fotografía de tu lectura',
            'Respaldo de nuestra llamada para que lo tengas guardado',
            'Llamada de 45min a 1hr',
            '3 preguntas por llamada',
          ],
        },
      ],
    },
    resourcesSection: {
      title: 'Recursos Educativos',
      subtitle: 'Formación y materiales prácticos para tu aprendizaje',
      ebookTitle: 'Guía para los Arcanos Mayores del Tarot',
      ebookDesc: 'Ebook para conocer el significado de los Arcanos Mayores. Una guía práctica de consulta y aprendizaje.',
      ebookPrice: '$11 USD',
      ebookCta: 'Comprar Ebook',
      courseTag: 'Curso Pre-grabado',
      courseTitle: 'El Tarot de la Acción',
      courseDesc: 'Curso pregrabado para aprender a leer el tarot en pro de la acción. En él encontrarás:',
      courseSyllabus: [
        'Introducción sobre el tarot y su historia.',
        'Significado de Arcanos Mayores y Menores.',
        'Ejercicios prácticos.',
        'Material didáctico, libros, PDFs y mazos para imprimir.',
      ],
      coursePrice: '$74 USD',
      courseCta: 'Comprar Curso',
    },
    aboutSection: {
      title: 'Sobre Pragmagicka',
      subtitle: 'Esoterismo Pragmático desde 2008',
      paragraphs: [
        'PRAGMAGICKA es la evolución directa de mi práctica espiritual, una donde lo fundamental es la fuerza de voluntad orientada a la acción a través de símbolos, rituales y herramientas esotéricas.',
        'Creo que no hay destino predeterminado ni cartas que adivinen el futuro. Hay decisiones que tomar y conflictos que destrabar. Muchas veces la mente estrictamente racional no basta para procesar dilemas internos que no siguen una lógica lineal. Es en ese espacio donde el esoterismo actúa como una tecnología pragmática, herramientas concretas para enfocar la mente, recuperar la agencia y accionar.',
        'Este proyecto condensa un recorrido de investigación y práctica continuada iniciado en 2008. No surge desde una torre de marfil ni desde el optimismo tóxico de la espiritualidad privilegiada. Entendemos que vivimos en un mundo cruzado por crisis económicas, desastres y precariedades. Es precisamente cuando el entorno es más hostil cuando la voluntad deja de ser un concepto abstracto y se convierte en una herramienta de supervivencia.',
        'Pragmagicka no promete soluciones mágicas a problemas estructurales; ofrece un marco funcional para operar en medio del caos.',
      ],
      authorTitle: 'Creado y guiado por Lorena Orlando',
      authorLocation: 'Investigadora, tarotista y diseñadora',
    },
    footer: {
      branding: 'Pragmagicka — Esoterismo Pragmático',
      contactTitle: 'Contacto',
      whatsapp: '+57 3138642943',
      email: 'soylorenaorlando@gmail.com',
      instagram: 'https://instagram.com/pragmagicka',
      credits: 'Pragmagicka 2026 - Diseño web por Lorena Orlando (lorenaorlando.click)',
    },
    modal: {
      title: 'Información',
      close: 'Cerrar',
      sectionPhilosophy: 'Manifiesto & Propósito',
      philosophyText: 'PRAGMAGICKA nace como una respuesta editorial y funcional al esoterismo tradicional. Los símbolos no buscan predecir el destino, sino servir de interfaces cognitivas para clarificar el pensamiento, destrabar bloqueos y catalizar la toma de decisiones prácticas.',
      techStackTitle: 'Diseño & Filosofía Visual',
      techStackText: 'Diseño gráfico editorial de corte limpio, franjas monocromáticas y de acento de borde a borde (#ffff0f y #bae9ee), tipografía dual (Viaoda Libre + DM Sans) y acabados de alta legibilidad.',
      authorByline: 'Diseño y conceptualización por Lorena Orlando',
    },
    bookingModal: {
      title: 'Solicitar Lectura de Tarot',
      titleProduct: 'Comprar Recurso Educativo',
      step1: '1. Opción seleccionada',
      step2: '2. Contacto directo e instrucciones',
      instruction: 'Para agendar tu sesión o adquirir el recurso, puedes escribir directamente por WhatsApp con el mensaje preformateado o enviar un correo electrónico.',
      whatsappCta: 'Contactar por WhatsApp',
      emailCta: 'Enviar Correo',
      priceTag: 'Inversión total',
      close: 'Volver',
    },
  },
  eng: {
    siteTitle: 'PRAGMAGICKA',
    subtitle: 'Magic and action',
    heroSubtitle: 'Magic and action',
    heroBody: 'Technology & magic to make decisions, unblock the mind, and take real-world action. No fortune-telling. No false promises.',
    nav: {
      tarot: 'Tarot Readings',
      resources: 'Educational Resources',
      about: 'About Pragmagicka',
      info: 'Info',
    },
    tarotSection: {
      title: 'Tarot Readings',
      subtitle: 'Understand your processes and how to act in favor of your goals. Resolve doubts and know yourself better.',
      additionalQuestionNotice: 'Asking more than 1 question carries an additional fee.',
      bookButton: 'Book Reading',
      plans: [
        {
          id: 'tarot-written',
          title: 'Written Reading',
          priceUSD: 29,
          format: 'written' as const,
          questionsCount: 1,
          features: [
            'Photograph of your spread',
            'A beautiful PDF with all the answers',
            '1 question per reading (additional questions carry an extra fee)',
          ],
        },
        {
          id: 'tarot-voice',
          title: 'Voice Note Reading',
          priceUSD: 56,
          format: 'voice' as const,
          questionsCount: 1,
          popular: true,
          features: [
            'Photograph of your spread',
            'Audio backup in case you lose it and need it back',
            '1 question per reading (additional questions carry an extra fee)',
          ],
        },
        {
          id: 'tarot-videocall',
          title: 'Videocall Reading',
          priceUSD: 83,
          format: 'videocall' as const,
          questionsCount: 3,
          duration: '45min to 1hr',
          features: [
            'Photograph of your spread',
            'Recording backup of our call to keep for future reference',
            'Live 45min to 1hr session',
            '3 questions per call',
          ],
        },
      ],
    },
    resourcesSection: {
      title: 'Educational Resources',
      subtitle: 'Learning guides and practical materials for your practice',
      ebookTitle: 'Guide to Tarot Major Arcana',
      ebookDesc: 'Ebook to understand the meaning of the Major Arcana. A practical handbook for study and consultation.',
      ebookPrice: '$11 USD',
      ebookCta: 'Buy Ebook',
      courseTag: 'Pre-recorded Course',
      courseTitle: 'Tarot of Action',
      courseDesc: 'Pre-recorded course to learn how to read tarot in favor of action. Inside you will find:',
      courseSyllabus: [
        'Introduction to tarot and its history.',
        'Meanings of Major and Minor Arcana.',
        'Practical reading exercises.',
        'Didactic material, books, PDFs, and printable decks.',
      ],
      coursePrice: '$74 USD',
      courseCta: 'Buy Course',
    },
    aboutSection: {
      title: 'About Pragmagicka',
      subtitle: 'Pragmatic Esotericism since 2008',
      paragraphs: [
        'PRAGMAGICKA is the direct evolution of my spiritual practice, where the foundation is willpower oriented toward action through symbols, rituals, and esoteric tools.',
        'I believe there is no predetermined destiny and no cards that predict the future. There are decisions to be made and conflicts to be unblocked. Often, the strictly rational mind is insufficient to process inner dilemmas that follow a non-linear logic. It is in that space where esotericism acts as a pragmatic technology—concrete tools to focus the mind, reclaim agency, and take action.',
        'This project condenses a continuous path of research and practice begun in 2008. It does not emerge from an ivory tower or the toxic optimism of privileged spirituality. We understand that we live in a world crossed by economic crises, disasters, and precarity. It is precisely when the environment is most hostile that willpower ceases to be an abstract concept and becomes a survival tool.',
        'Pragmagicka does not promise magical solutions to structural problems; it offers a functional framework to operate amid chaos.',
      ],
      authorTitle: 'Created and guided by Lorena Orlando',
      authorLocation: 'Researcher, tarotist, and designer',
    },
    footer: {
      branding: 'Pragmagicka — Pragmatic Esotericism',
      contactTitle: 'Contact',
      whatsapp: '+57 3138642943',
      email: 'soylorenaorlando@gmail.com',
      instagram: 'https://instagram.com/pragmagicka',
      credits: 'Pragmagicka 2026 - Web design by Lorena Orlando (lorenaorlando.click)',
    },
    modal: {
      title: 'Information',
      close: 'Close',
      sectionPhilosophy: 'Manifesto & Purpose',
      philosophyText: 'PRAGMAGICKA emerges as an editorial and functional response to traditional esotericism. Symbols do not seek to predict destiny, but serve as cognitive interfaces to clarify thought, unblock inertia, and catalyze practical decisions.',
      techStackTitle: 'Design & Visual System',
      techStackText: 'Clean editorial graphic design, full-width monochromatic and accent strips (#ffff0f and #bae9ee), dual typography (Viaoda Libre + DM Sans), and high contrast readability.',
      authorByline: 'Design and conceptualization by Lorena Orlando',
    },
    bookingModal: {
      title: 'Request Tarot Reading',
      titleProduct: 'Purchase Educational Resource',
      step1: '1. Selected Option',
      step2: '2. Direct Contact & Instructions',
      instruction: 'To book your session or purchase the resource, you can write directly via WhatsApp with a prefilled message or send an email.',
      whatsappCta: 'Contact via WhatsApp',
      emailCta: 'Send Email',
      priceTag: 'Total Investment',
      close: 'Back',
    },
  },
};
